### ISSUE TITLE
Game crashes when playing Blast Processing

### ISSUE THREAD

**Issue by comav** [camila314/BetterLoading#1]
Platform: Windows 10
Geode version: 1.3.5
BetterLoading version: 1.0.2-beta

The game crashes immediately after pressing "Blast Processing" in the menu

[2023-10-09_02-59-05.log](https://github.com/camila314/BetterLoading/files/12842042/2023-10-09_02-59-05.log)

**Comment by iwalfy** [comment]
same on toe 2
[Geode 30 Oct 11.53.04.log](https://github.com/camila314/BetterLoading/files/13203113/Geode.30.Oct.11.53.04.log)
